---
title: "Introduction, historical development of public administration and management, and recent critiques"
date: "2025-08-28"
---

## Readings

- The [syllabus](/syllabus.qmd), [class](/class/index.qmd), and [assignments](/assignment/index.qmd) pages for this class

- {{< fa file-pdf >}}&ensp;[@Nelson:2021]

- {{< fa file-pdf >}}&ensp;The "How to Read" section in [@Green:2021]

- {{< fa file-pdf >}}&ensp;[@HicksHumphriesSlater:2024]

- {{< fa external-link-square-alt >}}&ensp;[@Rosenzweig:2023]

- {{< fa file-pdf >}}&ensp;[@MeierHill:2005]

### Optional, but useful

- {{< fa file-pdf >}}&ensp;[@Powner:2016]


## Materials for today

- [**Slides**](/slides/2025-08-28.html)

- **How the class works**

- **Things they don’t teach you in grad school**

  - **How to read and annotate an article**

    - [Zotero](https://www.zotero.org/) + [Zotero Connector](https://www.zotero.org/download/connectors) + [GSU's Zotero guide](https://research.library.gsu.edu/zotero)
    - [Class Zotero group library](https://www.zotero.org/groups/governancef25)
    - [What are DOIs?](https://apastyle.apa.org/style-grammar-guidelines/references/dois-urls)
    - Taking and storing notes:
      - [Zotero](https://www.zotero.org/)
      - [Obsidian](https://obsidian.md/)
      - [Notion](https://www.notion.so/)
      - [OneNote](https://www.onenote.com/?public=1)
      - [Evernote](https://evernote.com/)
    - Things we'll read together:
      - {{< fa file-pdf >}}&ensp;[@Suzuki:2025]
      - {{< fa file-pdf >}}&ensp;[@MilwardJensenRoberts:2016]
        - Specifically the essays by (1) Brint Milward, and (2) Laura Jensen

  - **How to summarize, synthesize, and write about articles**

    - [Zotero in Word](https://www.zotero.org/support/word_processor_plugin_usage) + [Zotero in Google Docs](https://www.zotero.org/support/google_docs) (+ Zotero [in RStudio](https://posit.co/blog/rstudio-1-4-preview-citations/) or [with Markdown in general](https://www.andrewheiss.com/blog/2023/01/08/bibdesk-to-zotero-pandoc/#example-workflow-with-quarto-r-markdown-pandoc))
    - [Summary vs. synthesis](https://www.youtube.com/watch?v=R_rnkM7jvlY) + [The Synthesis Test](https://www.youtube.com/watch?v=R_rnkM7jvlY&t=241s)

  - **How to discuss an article in a seminar**

  	- General summary of the article
  	- Strengths
  	- Weaknesses
  	- How does it connect to other readings?
  	- How does it connect to the broader course themes?
  	- How does it connect to current events?
  	- What does it add to our Global Bureaucracy Toolkit^™^?
