---
title: "Africa"
date: "2025-11-13"
---

## Readings

- {{< fa file-pdf >}}&ensp;[@Tapscott:2021]

- {{< fa file-pdf >}}&ensp;[@Brierley:2020]

- {{< fa file-pdf >}}&ensp;[@WilliamsYecalo-Tecle:2020]

- {{< fa file-pdf >}}&ensp;[@HassanOMealia:2020]

- {{< fa file-pdf >}}&ensp;[@Moscona:2025]


## Article discussion reminder

**How to discuss an article in a seminar**

- Who wrote the article? What’s their background?
- General summary of the article
- Strengths
- Weaknesses
- How does it connect to other readings?
- How does it connect to the broader course themes?
- How does it connect to current events?
- What does it add to our Global Bureaucracy Toolkit^™^?


## Plan for the day

- **Weber, Marx, Dependency Theory, and public administration outside of the OECD**

- **Hybrid and heterogenous Latin American bureaucracies**

- **Latin American public administration**

  - [@Chudnovsky:2021] and [@RamosMilanesi:2021]
  - [@Zurbriggen:2021]
  - [@MunoBriceno:2023]
  - [@PeetersCampos:2021]

- **Modernization theory**

- **African public administration**

  - [@Tapscott:2021]
  - [@Brierley:2020] + [Randomized Response Explained](https://www.youtube.com/watch?v=SD7EzSkBXug)
  - [@Moscona:2025]
  - [@WilliamsYecalo-Tecle:2020]
  - [@HassanOMealia:2020]
